/* ============================================================================
   VETCARE - MODULO: CITAS
   Objetos programables de Oracle (PL/SQL)
   Universidad: TECSUP - Curso: Base de Datos Avanzadas
   ============================================================================
   Contenido de este script:
     1. Creacion de tablas
     2. Procedimientos almacenados (2)
     3. Funciones (2)
     4. Triggers (2)
     5. Package Specification + Package Body (agrupa 2 procedimientos y
        2 funciones adicionales del modulo Citas)
     6. Datos de prueba y bloque de pruebas (DBMS_OUTPUT)
   ============================================================================ */

SET SERVEROUTPUT ON;

-- ============================================================================
-- 1. CREACION DE TABLAS
-- ============================================================================

DROP TABLE auditoria_citas CASCADE CONSTRAINTS;
DROP TABLE citas CASCADE CONSTRAINTS;
DROP TABLE mascotas CASCADE CONSTRAINTS;
DROP TABLE veterinarios CASCADE CONSTRAINTS;
DROP TABLE clientes CASCADE CONSTRAINTS;

CREATE TABLE clientes (
    id_cliente      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres         VARCHAR2(100) NOT NULL,
    apellidos       VARCHAR2(100) NOT NULL,
    tipo_documento  VARCHAR2(10)  DEFAULT 'DNI',
    num_documento   VARCHAR2(20)  NOT NULL UNIQUE,
    telefono        VARCHAR2(20),
    email           VARCHAR2(150)
);

CREATE TABLE veterinarios (
    id_veterinario  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres         VARCHAR2(100) NOT NULL,
    apellidos       VARCHAR2(100) NOT NULL,
    especialidad    VARCHAR2(100),
    telefono        VARCHAR2(20),
    email           VARCHAR2(150),
    activo          NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1))
);

CREATE TABLE mascotas (
    id_mascota          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente          NUMBER NOT NULL,
    nombre              VARCHAR2(100) NOT NULL,
    especie             VARCHAR2(50),
    raza                VARCHAR2(100),
    sexo                CHAR(1) DEFAULT 'M' CHECK (sexo IN ('M', 'H')),
    fecha_nacimiento    DATE,
    CONSTRAINT fk_mascota_cliente FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

CREATE TABLE citas (
    id_cita         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mascota      NUMBER NOT NULL,
    id_veterinario  NUMBER NOT NULL,
    fecha_cita      DATE NOT NULL,
    hora_cita       VARCHAR2(5) NOT NULL,      -- formato 'HH24:MI'
    motivo          VARCHAR2(200),
    estado          VARCHAR2(15) DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'ATENDIDA', 'CANCELADA')),
    creado_en       DATE DEFAULT SYSDATE,
    CONSTRAINT fk_cita_mascota FOREIGN KEY (id_mascota)
        REFERENCES mascotas(id_mascota) ON DELETE CASCADE,
    CONSTRAINT fk_cita_veterinario FOREIGN KEY (id_veterinario)
        REFERENCES veterinarios(id_veterinario)
);

-- Tabla de auditoria: registra cada cambio de estado de una cita
CREATE TABLE auditoria_citas (
    id_auditoria    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cita         NUMBER NOT NULL,
    estado_anterior VARCHAR2(15),
    estado_nuevo    VARCHAR2(15),
    usuario_bd      VARCHAR2(50),
    fecha_cambio    DATE DEFAULT SYSDATE,
    CONSTRAINT fk_auditoria_cita FOREIGN KEY (id_cita)
        REFERENCES citas(id_cita) ON DELETE CASCADE
);


-- ============================================================================
-- 2. PROCEDIMIENTOS ALMACENADOS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SP 1: sp_registrar_cita
-- Problema que resuelve: evita que dos citas se agenden con el mismo
-- veterinario, en la misma fecha y hora (doble reserva), centralizando la
-- validacion en la base de datos en lugar de dejarla solo en la aplicacion.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE sp_registrar_cita (
    p_id_mascota      IN  citas.id_mascota%TYPE,
    p_id_veterinario  IN  citas.id_veterinario%TYPE,
    p_fecha_cita      IN  citas.fecha_cita%TYPE,
    p_hora_cita       IN  citas.hora_cita%TYPE,
    p_motivo          IN  citas.motivo%TYPE,
    p_id_cita_out     OUT citas.id_cita%TYPE
) IS
    v_ocupado NUMBER;
    v_vet_activo NUMBER;
BEGIN
    -- Validar que el veterinario exista y este activo
    SELECT COUNT(*) INTO v_vet_activo
    FROM veterinarios
    WHERE id_veterinario = p_id_veterinario AND activo = 1;

    IF v_vet_activo = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El veterinario no existe o no esta activo.');
    END IF;

    -- Validar que no exista otra cita activa con el mismo veterinario,
    -- fecha y hora (doble reserva)
    SELECT COUNT(*) INTO v_ocupado
    FROM citas
    WHERE id_veterinario = p_id_veterinario
      AND fecha_cita = p_fecha_cita
      AND hora_cita = p_hora_cita
      AND estado IN ('PENDIENTE', 'CONFIRMADA');

    IF v_ocupado > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El veterinario ya tiene una cita en esa fecha y hora.');
    END IF;

    INSERT INTO citas (id_mascota, id_veterinario, fecha_cita, hora_cita, motivo, estado)
    VALUES (p_id_mascota, p_id_veterinario, p_fecha_cita, p_hora_cita, p_motivo, 'PENDIENTE')
    RETURNING id_cita INTO p_id_cita_out;

    COMMIT;
END sp_registrar_cita;
/


-- ----------------------------------------------------------------------------
-- SP 2: sp_actualizar_estado_cita
-- Problema que resuelve: aplica las reglas del negocio sobre los cambios de
-- estado de una cita (maquina de estados), evitando que una cita ya
-- "ATENDIDA" o "CANCELADA" (estados finales) vuelva a modificarse por error.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE sp_actualizar_estado_cita (
    p_id_cita     IN citas.id_cita%TYPE,
    p_nuevo_estado IN citas.estado%TYPE
) IS
    v_estado_actual citas.estado%TYPE;
BEGIN
    SELECT estado INTO v_estado_actual
    FROM citas
    WHERE id_cita = p_id_cita;

    IF v_estado_actual IN ('ATENDIDA', 'CANCELADA') THEN
        RAISE_APPLICATION_ERROR(-20003,
            'No se puede modificar una cita en estado final (' || v_estado_actual || ').');
    END IF;

    UPDATE citas
    SET estado = p_nuevo_estado
    WHERE id_cita = p_id_cita;

    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20004, 'La cita indicada no existe.');
END sp_actualizar_estado_cita;
/


-- ============================================================================
-- 3. FUNCIONES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- FN 1: fn_citas_pendientes_mascota
-- Problema que resuelve: entrega rapidamente cuantas citas pendientes tiene
-- una mascota, informacion usada por el reporte "citas pendientes por
-- mascota" y por alertas del panel administrativo.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_citas_pendientes_mascota (
    p_id_mascota IN citas.id_mascota%TYPE
) RETURN NUMBER IS
    v_total NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total
    FROM citas
    WHERE id_mascota = p_id_mascota
      AND estado = 'PENDIENTE';

    RETURN v_total;
END fn_citas_pendientes_mascota;
/


-- ----------------------------------------------------------------------------
-- FN 2: fn_disponibilidad_veterinario
-- Problema que resuelve: permite consultar, antes de agendar, si un
-- veterinario esta disponible en una fecha/hora especifica, evitando que el
-- usuario intente registrar una cita que sp_registrar_cita rechazara.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_disponibilidad_veterinario (
    p_id_veterinario IN citas.id_veterinario%TYPE,
    p_fecha_cita     IN citas.fecha_cita%TYPE,
    p_hora_cita      IN citas.hora_cita%TYPE
) RETURN VARCHAR2 IS
    v_ocupado NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_ocupado
    FROM citas
    WHERE id_veterinario = p_id_veterinario
      AND fecha_cita = p_fecha_cita
      AND hora_cita = p_hora_cita
      AND estado IN ('PENDIENTE', 'CONFIRMADA');

    IF v_ocupado > 0 THEN
        RETURN 'OCUPADO';
    ELSE
        RETURN 'DISPONIBLE';
    END IF;
END fn_disponibilidad_veterinario;
/


-- ============================================================================
-- 4. TRIGGERS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TRIGGER 1: trg_valida_fecha_cita
-- Problema que resuelve: garantiza la integridad de los datos impidiendo que
-- se registre o reprograme una cita con fecha anterior a hoy.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_valida_fecha_cita
BEFORE INSERT OR UPDATE OF fecha_cita ON citas
FOR EACH ROW
BEGIN
    IF :NEW.fecha_cita < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20010, 'No se puede agendar una cita en una fecha pasada.');
    END IF;
END trg_valida_fecha_cita;
/


-- ----------------------------------------------------------------------------
-- TRIGGER 2: trg_auditoria_estado_cita
-- Problema que resuelve: mantiene un historial de auditoria de cada cambio
-- de estado de una cita (quien y cuando la modifico), sin depender de que
-- la aplicacion lo registre manualmente.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_auditoria_estado_cita
AFTER UPDATE OF estado ON citas
FOR EACH ROW
WHEN (OLD.estado != NEW.estado)
BEGIN
    INSERT INTO auditoria_citas (id_cita, estado_anterior, estado_nuevo, usuario_bd, fecha_cambio)
    VALUES (:NEW.id_cita, :OLD.estado, :NEW.estado, USER, SYSDATE);
END trg_auditoria_estado_cita;
/


-- ============================================================================
-- 5. PACKAGE: pkg_gestion_citas
-- Agrupa procedimientos y funciones adicionales del modulo Citas
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PACKAGE SPECIFICATION
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_gestion_citas IS

    -- Reprograma una cita existente (cambia fecha/hora) validando
    -- disponibilidad del veterinario en el nuevo horario.
    PROCEDURE reprogramar_cita (
        p_id_cita        IN citas.id_cita%TYPE,
        p_nueva_fecha    IN citas.fecha_cita%TYPE,
        p_nueva_hora     IN citas.hora_cita%TYPE
    );

    -- Cancela una cita y registra el motivo en el campo "motivo"
    PROCEDURE cancelar_cita (
        p_id_cita     IN citas.id_cita%TYPE,
        p_motivo_cancelacion IN VARCHAR2
    );

    -- Retorna el total de citas registradas para una fecha especifica
    FUNCTION total_citas_dia (
        p_fecha IN DATE
    ) RETURN NUMBER;

    -- Retorna un cursor con las citas de un veterinario (para reportes)
    FUNCTION citas_por_veterinario (
        p_id_veterinario IN citas.id_veterinario%TYPE
    ) RETURN SYS_REFCURSOR;

END pkg_gestion_citas;
/

-- ----------------------------------------------------------------------------
-- PACKAGE BODY
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY pkg_gestion_citas IS

    PROCEDURE reprogramar_cita (
        p_id_cita        IN citas.id_cita%TYPE,
        p_nueva_fecha    IN citas.fecha_cita%TYPE,
        p_nueva_hora     IN citas.hora_cita%TYPE
    ) IS
        v_id_veterinario citas.id_veterinario%TYPE;
        v_disponibilidad VARCHAR2(15);
    BEGIN
        SELECT id_veterinario INTO v_id_veterinario
        FROM citas WHERE id_cita = p_id_cita;

        v_disponibilidad := fn_disponibilidad_veterinario(v_id_veterinario, p_nueva_fecha, p_nueva_hora);

        IF v_disponibilidad = 'OCUPADO' THEN
            RAISE_APPLICATION_ERROR(-20020, 'El veterinario ya tiene otra cita en ese nuevo horario.');
        END IF;

        UPDATE citas
        SET fecha_cita = p_nueva_fecha,
            hora_cita  = p_nueva_hora,
            estado     = 'PENDIENTE'
        WHERE id_cita = p_id_cita;

        COMMIT;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20021, 'La cita indicada no existe.');
    END reprogramar_cita;


    PROCEDURE cancelar_cita (
        p_id_cita     IN citas.id_cita%TYPE,
        p_motivo_cancelacion IN VARCHAR2
    ) IS
    BEGIN
        sp_actualizar_estado_cita(p_id_cita, 'CANCELADA');

        UPDATE citas
        SET motivo = motivo || ' | Cancelada: ' || p_motivo_cancelacion
        WHERE id_cita = p_id_cita;

        COMMIT;
    END cancelar_cita;


    FUNCTION total_citas_dia (
        p_fecha IN DATE
    ) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total
        FROM citas
        WHERE fecha_cita = TRUNC(p_fecha);

        RETURN v_total;
    END total_citas_dia;


    FUNCTION citas_por_veterinario (
        p_id_veterinario IN citas.id_veterinario%TYPE
    ) RETURN SYS_REFCURSOR IS
        v_cursor SYS_REFCURSOR;
    BEGIN
        OPEN v_cursor FOR
            SELECT c.id_cita, m.nombre AS mascota, c.fecha_cita, c.hora_cita, c.estado
            FROM citas c
            JOIN mascotas m ON m.id_mascota = c.id_mascota
            WHERE c.id_veterinario = p_id_veterinario
            ORDER BY c.fecha_cita DESC;

        RETURN v_cursor;
    END citas_por_veterinario;

END pkg_gestion_citas;
/


-- ============================================================================
-- 6. DATOS DE PRUEBA
-- ============================================================================

INSERT INTO clientes (nombres, apellidos, tipo_documento, num_documento, telefono, email)
VALUES ('Diro', 'Carrasco', 'DNI', '45678912', '987654321', 'diro@example.com');

INSERT INTO clientes (nombres, apellidos, tipo_documento, num_documento, telefono, email)
VALUES ('Ana', 'Salvador', 'DNI', '78945612', '955512345', 'ana@example.com');

INSERT INTO veterinarios (nombres, apellidos, especialidad, telefono, email, activo)
VALUES ('Lucia', 'Fernandez', 'Medicina General', '999111222', 'lucia.fernandez@vetcare.com', 1);

INSERT INTO veterinarios (nombres, apellidos, especialidad, telefono, email, activo)
VALUES ('Marco', 'Ruiz', 'Cirugia', '999333444', 'marco.ruiz@vetcare.com', 1);

INSERT INTO mascotas (id_cliente, nombre, especie, raza, sexo, fecha_nacimiento)
VALUES (1, 'Rocky', 'Perro', 'Labrador', 'M', DATE '2021-05-10');

INSERT INTO mascotas (id_cliente, nombre, especie, raza, sexo, fecha_nacimiento)
VALUES (2, 'Michi', 'Gato', 'Siames', 'H', DATE '2022-02-20');

COMMIT;


-- ============================================================================
-- 7. BLOQUE DE PRUEBAS
-- ============================================================================

-- --- Prueba 1: registrar una cita correctamente -----------------------------
DECLARE
    v_id_cita NUMBER;
BEGIN
    sp_registrar_cita(
        p_id_mascota     => 1,
        p_id_veterinario => 1,
        p_fecha_cita     => TRUNC(SYSDATE) + 1,
        p_hora_cita      => '10:00',
        p_motivo         => 'Control anual',
        p_id_cita_out    => v_id_cita
    );
    DBMS_OUTPUT.PUT_LINE('Prueba 1 OK -> Cita registrada con id: ' || v_id_cita);
END;
/

-- --- Prueba 2: intentar doble reserva (debe fallar con -20002) --------------
DECLARE
    v_id_cita NUMBER;
BEGIN
    sp_registrar_cita(
        p_id_mascota     => 2,
        p_id_veterinario => 1,
        p_fecha_cita     => TRUNC(SYSDATE) + 1,
        p_hora_cita      => '10:00',
        p_motivo         => 'Vacunacion',
        p_id_cita_out    => v_id_cita
    );
    DBMS_OUTPUT.PUT_LINE('Prueba 2 -> No debio llegar aqui.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Prueba 2 OK (esperado) -> ' || SQLERRM);
END;
/

-- --- Prueba 3: funcion de disponibilidad ------------------------------------
DECLARE
    v_resultado VARCHAR2(15);
BEGIN
    v_resultado := fn_disponibilidad_veterinario(1, TRUNC(SYSDATE) + 1, '10:00');
    DBMS_OUTPUT.PUT_LINE('Prueba 3 -> Disponibilidad Dra. Fernandez 10:00: ' || v_resultado);

    v_resultado := fn_disponibilidad_veterinario(1, TRUNC(SYSDATE) + 1, '11:00');
    DBMS_OUTPUT.PUT_LINE('Prueba 3 -> Disponibilidad Dra. Fernandez 11:00: ' || v_resultado);
END;
/

-- --- Prueba 4: actualizar estado de cita (dispara el trigger de auditoria) --
BEGIN
    sp_actualizar_estado_cita(1, 'CONFIRMADA');
    DBMS_OUTPUT.PUT_LINE('Prueba 4 OK -> Estado de la cita 1 actualizado a CONFIRMADA.');
END;
/

-- --- Prueba 5: verificar que el trigger de auditoria registro el cambio -----
DECLARE
    v_total NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_total FROM auditoria_citas WHERE id_cita = 1;
    DBMS_OUTPUT.PUT_LINE('Prueba 5 OK -> Registros de auditoria para la cita 1: ' || v_total);
END;
/

-- --- Prueba 6: funcion de conteo de citas pendientes por mascota ------------
DECLARE
    v_total NUMBER;
BEGIN
    v_total := fn_citas_pendientes_mascota(1);
    DBMS_OUTPUT.PUT_LINE('Prueba 6 -> Citas pendientes de Rocky: ' || v_total);
END;
/

-- --- Prueba 7: intentar registrar una cita con fecha pasada (dispara trigger,
--     debe fallar con -20010) -----------------------------------------------
DECLARE
    v_id_cita NUMBER;
BEGIN
    sp_registrar_cita(
        p_id_mascota     => 2,
        p_id_veterinario => 2,
        p_fecha_cita     => TRUNC(SYSDATE) - 5,
        p_hora_cita      => '09:00',
        p_motivo         => 'Prueba fecha invalida',
        p_id_cita_out    => v_id_cita
    );
    DBMS_OUTPUT.PUT_LINE('Prueba 7 -> No debio llegar aqui.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Prueba 7 OK (esperado) -> ' || SQLERRM);
END;
/

-- --- Prueba 8: package - reprogramar cita -----------------------------------
BEGIN
    pkg_gestion_citas.reprogramar_cita(1, TRUNC(SYSDATE) + 2, '15:30');
    DBMS_OUTPUT.PUT_LINE('Prueba 8 OK -> Cita 1 reprogramada.');
END;
/

-- --- Prueba 9: package - cancelar cita --------------------------------------
DECLARE
    v_id_cita NUMBER;
BEGIN
    sp_registrar_cita(2, 2, TRUNC(SYSDATE) + 3, '09:00', 'Desparasitacion', v_id_cita);
    pkg_gestion_citas.cancelar_cita(v_id_cita, 'El cliente reagendara la proxima semana');
    DBMS_OUTPUT.PUT_LINE('Prueba 9 OK -> Cita ' || v_id_cita || ' cancelada.');
END;
/

-- --- Prueba 10: package - total de citas por dia ----------------------------
DECLARE
    v_total NUMBER;
BEGIN
    v_total := pkg_gestion_citas.total_citas_dia(TRUNC(SYSDATE) + 2);
    DBMS_OUTPUT.PUT_LINE('Prueba 10 -> Total de citas para ' || TO_CHAR(TRUNC(SYSDATE) + 2, 'DD/MM/YYYY') || ': ' || v_total);
END;
/

-- --- Prueba 11: package - cursor de citas por veterinario -------------------
DECLARE
    v_cursor SYS_REFCURSOR;
    v_id_cita citas.id_cita%TYPE;
    v_mascota mascotas.nombre%TYPE;
    v_fecha   citas.fecha_cita%TYPE;
    v_hora    citas.hora_cita%TYPE;
    v_estado  citas.estado%TYPE;
BEGIN
    v_cursor := pkg_gestion_citas.citas_por_veterinario(1);
    DBMS_OUTPUT.PUT_LINE('Prueba 11 -> Citas de la Dra. Fernandez:');
    LOOP
        FETCH v_cursor INTO v_id_cita, v_mascota, v_fecha, v_hora, v_estado;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('   Cita #' || v_id_cita || ' - ' || v_mascota ||
                              ' - ' || TO_CHAR(v_fecha, 'DD/MM/YYYY') || ' ' || v_hora ||
                              ' - ' || v_estado);
    END LOOP;
    CLOSE v_cursor;
END;
/

-- --- Consulta final: ver el estado completo de las tablas -------------------
SELECT * FROM citas ORDER BY id_cita;
SELECT * FROM auditoria_citas ORDER BY id_auditoria;
